Fix call for spanning-tree commands in dump script (#3723)
What I did
Fix the calls for spanning-tree commands in dump script.
During call to generate techsupport, we can see that the spanning tree commands fail:

.
Error: No such command "spanning_tree".
timeout --foreground 5m bash -c "dummy_cleanup_method ()
.
How I did it
Change from show spanning_tree to the actual command show spanning-tree

How to verify it
Call show techsupport