Add namespace support for show interface neighbor expected (#3781)
What I did
Adding namespace support for show interface neighbor expected. So that we can use

show interface neighbor expected -n asic0
How I did it
How to verify it
Verified on T2 testbed

Previous command output (if the output of a command-line utility has changed)
admin@somehost:/var/log$ show interfaces neighbor expected -n asic1
Usage: show interfaces neighbor expected [OPTIONS] [INTERFACENAME]
Try "show interfaces neighbor expected -h" for help.

Error: no such option: -n
New command output (if the output of a command-line utility has changed)
admin@somehost:/var/log$ show interfaces neighbor expected -n asic1
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet96   ARISTAXXTX  Ethernet1       None                XXX.XX.XXX.XX   someHub
Ethernet104  ARISTAXXTX Ethernet1       None                XXX.XX.XXX.XX   otherHub
...

Signed-off-by: Austin Pham <austinpham@microsoft.com>