static_route: prevent duplicate next hops by adding a missing guard
If a route is added with identical nexthop, route command must reject
it.

Before fix:
config route add prefix vrf Vrf_test 30.30.30.0/24 nexthop 10.10.10.2
config route add prefix vrf Vrf_test 30.30.30.0/24 nexthop 10.10.10.2
config route add prefix vrf Vrf_test 30.30.30.0/24 nexthop 10.10.10.2

  "STATIC_ROUTE|Vrf_test|30.30.30.0/24": {
    "type": "hash",
    "value": {
      "blackhole": "false,false,false",
      "distance": "0,0,0",
      "ifname": ",",
      "nexthop": "10.10.10.2,10.10.10.2,10.10.10.2",
      "nexthop-vrf": "Vrf_test,Vrf_test,Vrf_test"
    }

After fix:
config route add prefix vrf Vrf_test 30.30.30.0/24 nexthop 10.10.10.2
Usage: config route add [OPTIONS] prefix [vrf <vrf_name>] <A.B.C.D/M> nexthop
                        [vrf <vrf_name>]                 <A.B.C.D>|<dev
                        <dev_name>>|<A.B.C.D dev <dev_name>>
Try 'config route add -h' for help.

Error: Nexthop ('10.10.10.2', 'Vrf_test', '') already exists for route Vrf_test|30.30.30.0/24

Signed-off-by: Ravi Minnikanti <rminnikanti@marvell.com>