Fix counterpoll CLI to allow global namespace on Multi-Asic
CLI does not allow the empty '' global namespace and this causes MGMT test failures.

And requesting backport for
- [x] 202511

<!--
    Please make sure you've read and understood our contributing guidelines:
    https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

    ** Make sure all your commits include a signature generated with `git commit -s` **

    If this is a bug fix, make sure your description includes "closes #xxxx",
    "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
    issue when the PR is merged.

    If you are adding/modifying/removing any command or utility script, please also
    make sure to add/modify/remove any unit tests from the tests
    directory as appropriate.

    If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
    subcommand, or you are adding a new subcommand, please make sure you also
    update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
    your changes.

    Please provide the following information:
-->

#### What I did
Added a new function which will include the global namespace as a valid namespace option on multi-asic when the command is not run within a namespace.

#### Previous command output (if the output of a command-line utility has changed)
`counterpoll queue enable`
```
Usage: counterpoll queue [OPTIONS] COMMAND [ARGS]...
Try 'counterpoll queue --help' for help.

Error: Invalid value for '-n' / '--namespace': '' is not one of 'asic0', 'asic1'.
```

#### New command output (if the output of a command-line utility has changed)
(No output, success)

Signed-off-by: Sonic Build Admin <sonicbld@microsoft.com>